heat_template_version: 2013-05-23

description: Child stack for salt minions.

parameters:
  private_key:
    type: string
    description: Private key used to talk to other instances in same stack.
  public_key:
    type: string
    description: Public key used to talk to other instances in same stack.
  flavor:
    type: string
    description: Flavor to use
  image:
    type: string
    description: Image name
  network:
    type: string
    description: Network to use with minion
  master:
    type: string
    description: Salt-master location
  minion-config:
    type: string
    description: minion software config
  minion-roles:
    type: string
    description: List of roles for the minion

resources:

  deploy-salt-minion:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        public_key:
          get_param: public_key
        master:
          get_param: master
      config:
        get_param: minion-config
      server:
        get_resource: minion 

  minion:
    type: OS::Nova::Server
    properties:

      image: 
        get_param: image

      flavor:
        get_param: flavor

      personality:
        /root/.ssh/coms_rsa:
          get_param: private_key
        /etc/salt/grains:
          str_replace:
            template: "roles: [$roles]"
            params:
              $roles:
                get_param: minion-roles
           
      networks:
        - network: 
            get_param: network

      user_data_format: SOFTWARE_CONFIG

outputs:
  minion-ip:
    value:
      get_attr:
        - minion
        - first_address
  minion-stdout:
    value:
      get_attr:
        - deploy-salt-minion
        - deploy_stdout
  minion-stderr:
    value:
      get_attr:
        - deploy-salt-minion
        - deploy_stderr
